name: fixiproject
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.0.0+1

environment:
  sdk: ^3.10.7

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints.
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is included.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/carpenter.jpg
    - assets/welding.jpg
    - assets/plumber.jpg
    - assets/electrician.jpg
    - assets/Fixit_logo.png

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package